server:
  port: ${AUTH_SERVICE_PORT:8080}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${AUTH_DB_NAME:auth_db}
    username: ${DB_USERNAME:second_shelf}
    password: ${DB_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

internal:
  token: ${INTERNAL_TOKEN:internal-secret-123}

user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://localhost:8081}

jwt:
  secret: ${JWT_SECRET:change_this_secret_to_something_long_and_random_1234567890_change_me}
  expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:2592000000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true