server:
  port: ${EXCHANGE_SERVICE_PORT:8083}

spring:
  application:
    name: exchange-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${EXCHANGE_DB_NAME:exchange_db}
    username: ${DB_USERNAME:second_shelf}
    password: ${DB_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

internal:
  token: ${INTERNAL_TOKEN:internal-secret-123}

book-service:
  base-url: ${BOOK_SERVICE_BASE_URL:http://localhost:8082}

jwt:
  secret: ${JWT_SECRET:change_this_secret_to_something_long_and_random_1234567890_change_me}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true