spring:
  datasource:
    password: ${DB_PASSWORD:secret}
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

internal:
  token: ${INTERNAL_TOKEN:internal-secret-123}

jwt:
  secret: ${JWT_SECRET:change_this_secret_to_something_long_and_random_1234567890_change_me}
