package com.secondshelf.notificationservice.entity;

public enum NotificationType {
    GENERIC,
    EXCHANGE_REQUEST_CREATED,
    EXCHANGE_REQUEST_ACCEPTED,
    EXCHANGE_REQUEST_DECLINED,
    EXCHANGE_REQUEST_CANCELLED,
    EXCHANGE_REQUEST_COMPLETION_CONFIRMED,
    EXCHANGE_REQUEST_COMPLETED
}
